# Generated by Django 4.0.4 on 2022-05-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_input',
            name='name',
            field=models.TextField(default='data'),
        ),
        migrations.AddField(
            model_name='data_input',
            name='position',
            field=models.TextField(default='data'),
        ),
    ]
