# Generated by Django 4.0.4 on 2022-05-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipapp', '0002_data_input_name_data_input_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Searched_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('continent', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('country_code', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=200)),
                ('region_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='data_input',
        ),
    ]
