# Generated by Django 4.0.4 on 2022-05-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipapp', '0003_searched_data_delete_data_input'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_label', models.CharField(default='label', max_length=200, null=True, unique=True)),
                ('chart_number', models.IntegerField(default='0', null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='searched_data',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='searched_data',
            name='continent',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='searched_data',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='searched_data',
            name='country_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='searched_data',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='searched_data',
            name='region',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='searched_data',
            name='region_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
