# Generated by Django 4.0.4 on 2022-05-31 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipapp', '0004_chart_data_alter_searched_data_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chart_data',
        ),
    ]
