# Generated by Django 4.0.4 on 2022-05-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipapp', '0006_chart_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart_table',
            name='data',
            field=models.IntegerField(null=True),
        ),
    ]
