# Generated by Django 4.0.4 on 2022-05-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipapp', '0007_alter_chart_table_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='searched_data',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
