# Generated by Django 4.0.4 on 2022-06-01 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipapp', '0009_chart_table_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searched_data',
            options={'verbose_name_plural': 'Searched_data'},
        ),
    ]
