# Generated by Django 4.0.4 on 2022-06-01 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipapp', '0010_alter_searched_data_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chart_table',
            options={'verbose_name_plural': 'Job Postings'},
        ),
        migrations.AlterModelOptions(
            name='searched_data',
            options={},
        ),
    ]
