# Generated by Django 4.0.4 on 2022-06-01 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipapp', '0011_alter_chart_table_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chart_table',
            options={'verbose_name_plural': 'job'},
        ),
    ]
