# Generated by Django 4.0.4 on 2022-06-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipapp', '0012_alter_chart_table_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chart_table',
            options={'verbose_name_plural': 'chart_table'},
        ),
        migrations.AlterModelOptions(
            name='searched_data',
            options={'verbose_name_plural': 'searched api info'},
        ),
        migrations.AddField(
            model_name='searched_data',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='searched_data',
            name='lng',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='chart_table',
            name='data',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='chart_table',
            name='label',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='chart_table',
            name='user',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
