# Generated by Django 4.0.4 on 2022-06-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipapp', '0013_alter_chart_table_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart_table',
            name='data',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='chart_table',
            name='label',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chart_table',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
