# Generated by Django 4.0.4 on 2022-06-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipapp', '0014_alter_chart_table_data_alter_chart_table_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart_table',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='chart_table',
            name='lng',
            field=models.FloatField(default=0),
        ),
    ]
